// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Infrastructure.Data.Database.Configurations;
using Infrastructure.Data.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using System;
using System.Collections.Generic;
#nullable disable

namespace Infrastructure.Data.Database
{
    public partial class MyBankContext : DbContext
    {
        public MyBankContext()
        {
        }

        public MyBankContext(DbContextOptions<MyBankContext> options)
            : base(options)
        {
        }

        public virtual DbSet<cartao_credito> cartao_credito { get; set; }
        public virtual DbSet<extrato_cartao> extrato_cartao { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new Configurations.cartao_creditoConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.extrato_cartaoConfiguration());

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
