// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure.Data.Entity
{
    public partial class cartao_credito
    {
        public cartao_credito()
        {
            extrato_cartao = new HashSet<extrato_cartao>();
        }

        public Guid id_cartao { get; set; }
        public string nome_cartao { get; set; }
        public string emissor { get; set; }
        public string bandeira { get; set; }
        public decimal? limite { get; set; }
        public bool? status { get; set; }

        public virtual ICollection<extrato_cartao> extrato_cartao { get; set; }
    }
}