// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure.Data.Entity
{
    public partial class extrato_cartao
    {
        public int Id { get; set; }
        public DateTime data { get; set; }
        public string descricao { get; set; }
        public Guid? id_cartao { get; set; }
        public decimal? valor { get; set; }
        public DateTime? fatura { get; set; }
        public bool? status_fatura { get; set; }
        public DateTime? data_pgto_fatura { get; set; }
        public int? categoria { get; set; }

        public virtual cartao_credito id_cartaoNavigation { get; set; }
    }
}